# fg_bgmc_movieLib.R  
# Author: Eason Li
# Date: 12/14/2021

#-----main functions-----
all_tests_main = function()
{ 
  # cut and paste into the R-shell any group of these commands
  source("~/__init_rBed_01.R")
  rBedPath = glob[["rBedPath"]]  
  glob[["workDir"]] = paste0(rBedPath, "/rBed_bgmc", "/bgmc_movieLib", "/workDir") 
  setwd(glob[["workDir"]])
  dataDir     = paste0(rBedPath, "/rBed_bgmc/bgmc_movieLib/movieLib/") 
  
  func_bgmc_movieLib_dt_exp(instanceDir=dataDir, numberOfMovies=10, lower_bound=10, 
                            upper_bound=20, isRDS=T)
  func_bgmc_movieLib_df_exp(instanceDir=dataDir, numberOfMovies=10, lower_bound=10, 
                            upper_bound=20, isRDS=TRUE)
  
  movieDef = paste0(dataDir, "movieRecords_4.csv")
  watchDef = paste0(dataDir, "watchRecords_4.csv")
  
  func_top_movie_df(numberOfMovies=10, movieDef, watchDef)
  func_top_movie_dt(numberOfMovies=10, movieDef, watchDef)
  
  
    
} # all_tests_main

func_bgmc_movieLib_dt_exp = function(instanceDir, numberOfMovies, lower_bound=2, 
                                     upper_bound=6, isRDS=TRUE) {
  
  # Generate a data table that compares the elapsed time of reading files against 
  # the elapsed time of searching for the most popular movies based on file size
  thisFunction = "func_bgmc_movieLib_dt_exp"
  
  dtExp = data.table()
  
  files <- list.files(instanceDir)
  read_time_vec <- c()
  search_time_vec <- c()
  size_vec <- c()
  movie_vec <- c()
  watch_vec <- c()
  for (file in files) {
    if (substr(file,1,1) == "w") {
      watch_vec <- c(watch_vec, file)
    } else if (substr(file,1,1) == "m") {
      movie_vec <- c(movie_vec, file)
    }
  }
  i <- lower_bound
  # measure <- "sysTime"
  while (i <= upper_bound) {
    # print(paste("_", i, ".csv", sep = ""))
    movie_name <- ""
    watch_name <- ""
    time <- ""
    for (movie in movie_vec) {
      if (endsWith(movie, paste("_", i, ".csv", sep = ""))) {
        movie_name <- movie
        break
      }
    }
    for (watch in watch_vec) {
      if (endsWith(watch, paste("_", i, ".csv", sep = ""))) {
        watch_name <- watch
        break
      }
    }
    answ = func_top_movie_dt(numberOfMovies, paste(instanceDir, movie_name, sep = ""),
                             paste(instanceDir,watch_name, sep = ""))
    
    read_time_vec <- c(read_time_vec, answ$runtime_read)
    search_time_vec <- c(search_time_vec, answ$runtime_search)
    size_vec <- c(size_vec, i)
    i <- i + 2
  }
  
  dtExp <- data.table(`Size(2^x)` = size_vec, R_read_T = read_time_vec, R_search_T = search_time_vec)
  curpath = getwd()
  setwd(file.path(dirname(glob[["workDir"]]), "movieRDS"))
  if (isRDS) {
    fileRDS = "R_matrixS.RDS"
    saveRDS(dtExp, fileRDS)
    cat(sep="", "\n** saved a datatable generated by function ", thisFunction,
        "\n in the file = ", fileRDS, "\n",
        "\n Access the file with either as",
        "\n                 print(readRDS(\"", file.path(paste0(glob[["rBedPath"]],
                    "/rBed_bgmc", "/bgmc_movieLib", "/movieRDS"), fileRDS), "\"))",
        "\n or as",
        "\n               dtExp = readRDS(\"", file.path(paste0(glob[["rBedPath"]],
                    "/rBed_bgmc", "/bgmc_movieLib", "/movieRDS"), fileRDS), "\")",
        "\n")    
  } else {
    cat("\n** a datatable stdout generated by function", thisFunction, "**\n\n")
    print(dtExp)   
  }
  cat("\n.. returning from", thisFunction, "on", date(), "\n\n")
  setwd(curpath)
} # func_bgmc_movieLib_dt_exp

func_bgmc_movieLib_df_exp = function(instanceDir, numberOfMovies, lower_bound=2, 
                                     upper_bound=6, isRDS=TRUE) {
  # Generate a data frame that compares the elapsed time of reading files against 
  # the elapsed time of searching for the most popular movies based on file size
  thisFunction = "func_bgmc_movieLib_df_exp"
  
  files <- list.files(instanceDir)
  read_time_vec <- c()
  search_time_vec <- c()
  size_vec <- c()
  movie_vec <- c()
  watch_vec <- c()
  for (file in files) {
    if (substr(file,1,1) == "w") {
      watch_vec <- c(watch_vec, file)
    } else if (substr(file,1,1) == "m") {
      movie_vec <- c(movie_vec, file)
    }
  }
  i <- lower_bound
  # measure <- "sysTime"
  while (i <= upper_bound) {
    # print(paste("_", i, ".csv", sep = ""))
    movie_name <- ""
    watch_name <- ""
    time <- ""
    for (movie in movie_vec) {
      if (endsWith(movie, paste("_", i, ".csv", sep = ""))) {
        movie_name <- movie
        break
      }
    }
    for (watch in watch_vec) {
      if (endsWith(watch, paste("_", i, ".csv", sep = ""))) {
        watch_name <- watch
        break
      }
    }
    
    answ = func_top_movie_df(numberOfMovies, paste(instanceDir, movie_name, sep = ""),
                             paste(instanceDir,watch_name, sep = ""))
    
    read_time_vec <- c(read_time_vec, answ$runtime_read)
    search_time_vec <- c(search_time_vec, answ$runtime_search)
    size_vec <- c(size_vec, i)
    i <- i + 2
  }
  dtExp <- data.table(`Size(2^x)` = size_vec, R_read_M = read_time_vec, R_search_M = search_time_vec)
  curpath = getwd()
  setwd(file.path(dirname(glob[["workDir"]]), "movieRDS"))
  if (isRDS) {
    fileRDS = "R_matrixF.RDS"
    saveRDS(dtExp, fileRDS)
    cat(sep="", "\n** saved a datatable generated by function ", thisFunction,
        "\n in the file = ", fileRDS, "\n",
        "\n Access the file with either as",
        "\n                 print(readRDS(\"", file.path(paste0(glob[["rBedPath"]],
                                                                "/rBed_bgmc", "/bgmc_movieLib", "/movieRDS"), fileRDS), "\"))",
        "\n or as",
        "\n               dtExp = readRDS(\"", file.path(paste0(glob[["rBedPath"]],
                                                                "/rBed_bgmc", "/bgmc_movieLib", "/movieRDS"), fileRDS), "\")",
        "\n") 
  } else {
    cat("\n** a datatable stdout generated by function", thisFunction, "**\n\n")
    print(dtExp)   
  }
  cat("\n.. returning from", thisFunction, "on", date(), "\n\n")
  setwd(curpath)
} # func_bgmc_movieLib_df_exp

func_top_movie_dt = function(numberOfMovies, movieDef, watchDef) {
  
  # Retrieve the top movies using data table
  thisFunction = "func_top_movie_dt"
  runtime_read = system.time({
    movie_table <- fread(movieDef, fill = TRUE, sep = ",")
    watch_table <- fread(watchDef, fill = TRUE)
  })[["elapsed"]]
  
  runtime_search = system.time({
    if (numberOfMovies <= 0) {
      stop("Please enter a number > 0.\n")
    }
    
    if (!"VIEWERS"%in% colnames(watch_table)) {
      watch_table <- watch_table[, VIEWERS := 1:.N, by="MOVIE_ID"]
    }
    unique_watch_table <- unique(watch_table, by = "MOVIE_ID", fromLast = TRUE)
    sort_watch_table = unique_watch_table[order(-unique_watch_table$VIEWERS)]
    head_watch_table = head(sort_watch_table, numberOfMovies)
    
    dtExp = movie_table[with(movie_table, ID %in% head_watch_table$MOVIE_ID),]
    merge_table = merge(dtExp, head_watch_table, by.x ="ID", by.y = "MOVIE_ID")
    
    merge_table <- merge_table[order(-merge_table$VIEWERS, merge_table$TITLE, merge_table$ID)]
    merge_table <- merge_table[, c("ID", "TITLE", "YEAR", "VIEWERS")]
    
    if (nrow(merge_table) == 0) {
      return("No movies have been streamed.\n")
    }
    
  })[["elapsed"]]
  
  return(list(table = merge_table, runtime_read = runtime_read, runtime_search = runtime_search))
  
} # func_top_movie_dt

func_top_movie_df = function(numberOfMovies, movieDef, watchDef) {
  
  # Retrieve the top movies using data frame
  thisFunction = "func_top_movie_df"
  runtime_read = system.time({
    movie_table <- read.table(movieDef, fill = TRUE, sep = ",", header=T)
    watch_table <- read.table(watchDef, fill = TRUE, sep = ",", header=T)
  })[["elapsed"]]
  
  runtime_search = system.time({
    if (numberOfMovies <= 0) {
      return("Please enter a number > 0.\n")
    }
    watch_table$VIEWERS = 0
    # https://statisticsglobe.com/count-number-of-cases-within-each-group-of-data-frame-in-r
    watch_table = aggregate(VIEWERS ~ `MOVIE_ID`, data = watch_table, FUN = length)
    
    unique_watch_table <- unique(watch_table, by = "MOVIE_ID", fromLast = TRUE)
    sort_watch_table = unique_watch_table[order(-unique_watch_table$VIEWERS),]
    head_watch_table = head(sort_watch_table, numberOfMovies)
    
    dtExp = movie_table[with(movie_table, ID %in% head_watch_table$MOVIE_ID),]
    merge_table = merge(dtExp, head_watch_table, by.x ="ID", by.y = "MOVIE_ID")
    merge_table <- merge_table[order(-merge_table$VIEWERS, merge_table$TITLE, merge_table$ID),]
    merge_table <- merge_table[, c("ID", "TITLE", "YEAR", "VIEWERS")]
    
    if (nrow(merge_table) == 0) {
      return("No movies have been streamed.\n")
    }
    
  })[["elapsed"]]
  
  return(list(table = merge_table, runtime_read = runtime_read, runtime_search = runtime_search))
} # func_top_movie_df


#-----runtime experiments------
all_tests_runtime = function()
{ 
  # cut and paste into the R-shell any group of these commands
  source("~/__init_rBed_01.R")
  rBedPath = glob[["rBedPath"]]  
  glob[["workDir"]] = paste0(rBedPath, "/rBed_bgmc", "/bgmc_movieLib", "/workDir") 
  setwd(glob[["workDir"]])
  dataDir     = paste0(rBedPath, "/rBed_bgmc/bgmc_movieLib/movieLib/") 
  data_rBed_dir   = paste0(rBedPath, "/rBed_bgmc/bgmc_movieLib/movieRDS") 
  
  fg_bgmc_movieLib_runtime_init(data_rBed_dir)  
  fg_bgmc_movieLib_runtime_search(data_rBed_dir)
  fg_bgmc_movieLib_runtime_read(data_rBed_dir)
  fg_bgmc_movieLib_runtime_total_ab(data_rBed_dir)
  
} # all_tests_runtime

fg_bgmc_movieLib_runtime_init = function(data_rBed_dir) {
  
  # Generate a graph to compare the total runtime and file sizes, 
  # as well as the data table in R and the chain hash ADT in Java
  thisFunction = "fg_bgmc_movieLib_runtime_init"
  RDS_folder = c(file.path(data_rBed_dir, "Java_chainHash.RDS"),
                 file.path(data_rBed_dir, "R_matrixS.RDS"))
  
  dtExp = data.table()
  
  for (file in RDS_folder) {
    # print(str_split(file,"\\.")[[1]][1])
    dt = readRDS(file)
    colnames(dt) = c("size", "runtime_read", "runtime_search")
    legend = str_split(basename(file),"\\.")[[1]][1]
    dt$legend = legend
    dtExp = rbind(dtExp, dt)
  }
  
  dtExp$runtime_total = dtExp$runtime_read + dtExp$runtime_search
  print(dtExp)
  
  size = unique(dtExp$size)
  
  p1<-ggplot(dtExp, aes(x=size, y=runtime_total, color=legend)) +
    geom_line()  +
    scale_x_continuous("size of movieLib=2^(10:20)", labels = as.character(size), breaks = size) +
    theme(legend.position = c(0.3, 0.6), legend.key.size = unit(.3, 'inch'),
          legend.text = element_text(size=15),
          legend.title = element_blank())
  
  p = grid.arrange(p1, ncol=1, nrow=1,  
                   top = textGrob("fg_bgmc_movieLib_runtime_init", x = 0.07, hjust = 0,
                                  gp=gpar(fontsize=8,font=1, col="gray47")))
  
  ggsave("fg_bgmc_movieLib_runtime_init.pdf", p, width = 7, height = 4)
  
  cat("\n.. Figure saved in", glob[["workDir"]])
  cat("\n.. returning from", thisFunction, "on", date(), "\n\n")
} # fg_bgmc_movieLib_runtime_init

fg_bgmc_movieLib_runtime_total_ab = function(data_rBed_dir) {
  # Generate a graph (a) to compare the total runtime and file sizes , 
  # as well as 6 ADTs in Java
  # Generate a graph (b) to compare the total runtime and file sizes , 
  # as well as best ADT in Java with data table in R and data frame in R
  thisFunction = "fg_bgmc_movieLib_runtime_total_ab"
  RDS_folder = c(file.path(data_rBed_dir, "Java_chainHash.RDS"),
                 file.path(data_rBed_dir, "Java_hashMultiMap.RDS"),
                 file.path(data_rBed_dir, "Java_linearProbing.RDS"),
                 file.path(data_rBed_dir, "Java_linkedHashMultimap.RDS"))
  
  dtExp = data.table()
  
  for (file in RDS_folder) {
    # print(str_split(file,"\\.")[[1]][1])
    dt = readRDS(file)
    colnames(dt) = c("size", "runtime_read", "runtime_search")
    dt$legend = str_split(basename(file),"\\.")[[1]][1]
    dtExp = rbind(dtExp, dt)
  }
  
  dtExp$runtime_total = dtExp$runtime_read + dtExp$runtime_search
  print(dtExp)
  
  size = unique(dtExp$size)
  
  p1<-ggplot(dtExp, aes(x=size, y=runtime_total, color=legend)) +
    geom_line()  +
    scale_x_continuous("size of movieLib=2^(10:20)", labels = as.character(size), breaks = size) +
    labs(title = "(a)") +
    theme(legend.position = c(0.3, 0.6), legend.key.size = unit(.3, 'inch'),
          legend.text = element_text(size=15),
          plot.title = element_text(size=10, hjust = 0.5), 
          legend.title = element_blank())
  
  p = grid.arrange(p1, ncol=1, nrow=1,  
                   top = textGrob("fg_bgmc_movieLib_runtime_total", x = 0.19, y = -1,
                                  gp=gpar(fontsize=8,font=1, col="gray47")))
  
  
  ggsave("fg_bgmc_movieLib_runtime_total_a.pdf", p, width = 7, height = 4)
  
  
  RDS_folder = c(file.path(data_rBed_dir, "Java_chainHash.RDS"),
                 file.path(data_rBed_dir, "R_matrixS.RDS"),
                 file.path(data_rBed_dir, "R_matrixF.RDS"))
  
  dtExp = data.table()
  
  for (file in RDS_folder) {
    # print(str_split(file,"\\.")[[1]][1])
    dt = readRDS(file)
    colnames(dt) = c("size", "runtime_read", "runtime_search")
    dt$legend = str_split(basename(file),"\\.")[[1]][1]
    dtExp = rbind(dtExp, dt)
  }
  
  dtExp$runtime_total = dtExp$runtime_read + dtExp$runtime_search
  print(dtExp)
  
  size = unique(dtExp$size)
  
  p1<-ggplot(dtExp, aes(x=size, y=runtime_total, color=legend)) +
    geom_line()  +
    scale_x_continuous("size of movieLib=2^(10:20)", labels = as.character(size), breaks = size) +
    labs(title = "(b)") +
    theme(legend.position = c(0.3, 0.6), legend.key.size = unit(.3, 'inch'),
          legend.text = element_text(size=15),
          plot.title = element_text(size=10, hjust = 0.5), 
          legend.title = element_blank())
  
  p = grid.arrange(p1, ncol=1, nrow=1,  
                   top = textGrob("fg_bgmc_movieLib_runtime_total", x = 0.19, y = -1,
                                  gp=gpar(fontsize=8,font=1, col="gray47")))
  
  ggsave("fg_bgmc_movieLib_runtime_total_b.pdf", p, width = 7, height = 4)
  cat("\n.. Figure saved in", glob[["workDir"]])
  cat("\n.. returning from", thisFunction, "on", date(), "\n\n")
} # fg_bgmc_movieLib_runtime_total_ab
 
fg_bgmc_movieLib_runtime_search = function(data_rBed_dir) {
  # # Generate a graph to compare the search runtime and file sizes, 
  # as well as the data table in R, data frame in R and the chain hash ADT in Java
  thisFunction = "fg_bgmc_movieLib_runtime_search"
  RDS_folder = c(file.path(data_rBed_dir, "Java_chainHash.RDS"),
                 file.path(data_rBed_dir, "R_matrixS.RDS"),
                 file.path(data_rBed_dir, "R_matrixF.RDS"))
  
  dtExp = data.table()
  
  for (file in RDS_folder) {
    # print(str_split(file,"\\.")[[1]][1])
    dt = readRDS(file)
    colnames(dt) = c("size", "runtime_read", "runtime_search")
    dt$legend = str_split(basename(file),"\\.")[[1]][1]
    dtExp = rbind(dtExp, dt)
  }
  
  dtExp$runtime_total = dtExp$runtime_read + dtExp$runtime_search
  print(dtExp)
  
  size = unique(dtExp$size)
  
  p1<-ggplot(dtExp, aes(x=size, y=runtime_search, color=legend)) +
    geom_line()  +
    scale_x_continuous("size of movieLib=2^(10:20)", labels = as.character(size), breaks = size) +
    labs(title = "(d)") +
    theme(legend.position = c(0.3, 0.6), legend.key.size = unit(.3, 'inch'),
          legend.text = element_text(size=15),
          plot.title = element_text(size=10, hjust = 0.5), 
          legend.title = element_blank())
  
  p = grid.arrange(p1, ncol=1, nrow=1,  
                   top = textGrob("fg_bgmc_movieLib_runtime_search", x = 0.07, y = -1,
                                  hjust = 0,
                                  gp=gpar(fontsize=8,font=1, col="gray47")))
  
  ggsave("fg_bgmc_movieLib_runtime_search_d.pdf", p, width = 7, height = 4)
  cat("\n.. Figure saved in", glob[["workDir"]])
  cat("\n.. returning from", thisFunction, "on", date(), "\n\n")
} # fg_bgmc_movieLib_runtime_search

fg_bgmc_movieLib_runtime_read = function(data_rBed_dir) {
  # Generate a graph to compare the read runtime and file sizes, 
  # as well as the data table in R and the chain hash ADT in Java
  thisFunction = "fg_bgmc_movieLib_runtime_read"
  RDS_folder = c(file.path(data_rBed_dir, "Java_chainHash.RDS"),
                 file.path(data_rBed_dir, "R_matrixS.RDS"),
                 file.path(data_rBed_dir, "R_matrixF.RDS"))
  
  dtExp = data.table()
  
  for (file in RDS_folder) {
    # print(str_split(file,"\\.")[[1]][1])
    dt = readRDS(file)
    colnames(dt) = c("size", "runtime_read", "runtime_search")
    dt$legend = str_split(basename(file),"\\.")[[1]][1]
    dtExp = rbind(dtExp, dt)
  }
  
  dtExp$runtime_total = dtExp$runtime_read + dtExp$runtime_search
  print(dtExp)
  
  size = unique(dtExp$size)
  
  p1<-ggplot(dtExp, aes(x=size, y=runtime_read, color=legend)) +
    geom_line()  +
    scale_x_continuous("size of movieLib=2^(10:20)", labels = as.character(size), breaks = size) +
    labs(title = "(c)") +
    theme(legend.position = c(0.3, 0.6), legend.key.size = unit(.3, 'inch'),
          legend.text = element_text(size=15),
          plot.title = element_text(size=10, hjust = 0.5), 
          legend.title = element_blank())
  
  p = grid.arrange(p1, ncol=1, nrow=1,  
                   top = textGrob("fg_bgmc_movieLib_runtime_read", x = 0.19, y = -1,
                                  gp=gpar(fontsize=8,font=1, col="gray47")))
  
  
  ggsave("fg_bgmc_movieLib_runtime_read_c.pdf", p, width = 7, height = 4)
  cat("\n.. Figure saved in", glob[["workDir"]])
  cat("\n.. returning from", thisFunction, "on", date(), "\n\n")
} # fg_bgmc_movieLib_runtime_read



#-----movieLib data experiments----
all_tests_data = function() { 
  # cut and paste into the R-shell any group of these commands
  source("~/__init_rBed_01.R")
  rBedPath = glob[["rBedPath"]]  
  glob[["workDir"]] = paste0(rBedPath, "/rBed_bgmc", "/bgmc_movieLib", "/workDir") 
  setwd(glob[["workDir"]]) 
  dataDir     = paste0(rBedPath, "/rBed_bgmc/bgmc_movieLib/movieLib/") 
  
  urnSizes   = c(2^(10:20))
  trialSizes = c(2^(10:20))
  rds_urn_sample_withRepl(urnSizes, trialSizes, replicateSize=100)
  
  data_rBed_dir   = "../movieRDS"
  fileRDS_dtPairs = file.path(data_rBed_dir, "rds_urn_sample_withRepl_20_20_100_dtPairs.RDS")
  fileRDS_dt      = file.path(data_rBed_dir, "rds_urn_sample_withRepl_20_20_100_dt.RDS")
  fg_bgmc_movieLib_data_unwatched(fileRDS_dtPairs, fileRDS_dt)
  
  fg_bgmc_movieLib_data_unwatched_gg(fileRDS_dtPairs, fileRDS_dt)
  
  fg_bgmc_movieLib_a12()
  
  
  
} # all_tests_data

fg_bgmc_movieLib_data_unwatched_gg = function(fileRDS_dtPairs, fileRDS_dt){
  # a statistical model, based on 210 ... 220 trials of sampling with 
  # replacement from 11 urns, each with urn capacity of holding 210 ... 220 unique movieID tags.
  
  # Figure generated by ggplot2
  thisFunction = "fg_bgmc_movieLib_data_unwatched_gg"
  
  dtPairs = readRDS(fileRDS_dtPairs)
  dtE     = readRDS(fileRDS_dt)
  nRows   = nrow(dtE)
  
  # plot cover-vs-size
  x = as.integer(log2(dtE$urnSize)) ; y = dtE$couponsCover
  x_min = min(x)
  x_max = max(x)
  y_min = min(y)  ; cat("\n.. y_min =", y_min, "\n")
  y_max = max(y)  ; cat(".. y_max =", y_max, "\n\n") 
  
  dt = data.table(x=x, y=y)
  
  yW = watchedCover = 
    1 -  c(371/2^10, 1525/2^12, 6005/2^14, 24111/2^16, 96348/2^18, 386105/2^20)
  xW = c(10, 12, 14, 16, 18, 20) 
  
  
  highlight_dt= data.table(xW=xW, yW=yW)
  p1 = ggplot(data=dt, aes(x=x,y=y)) + 
    geom_point(shape=1) + 
    labs(x=paste("capacity of urns = 2^(10:20)", sep=""),
         y=paste("fraction of unique movieIDs drawn with replacement after 2^(10:20) trials",
                 sep=""),
         title = "(c)") +
    scale_x_continuous(labels = as.character(xW), breaks = xW) +
    geom_hline(yintercept=1 - exp(-1), linetype="dashed", color = "red") +
    geom_point(data=highlight_dt, 
               aes(x=xW,y=yW,colour="values observed from movieLib"), 
               # color='red',
               size=3) +
    theme(legend.position = c(0.6, 0.2), legend.key.size = unit(1, 'cm'),
          legend.text = element_text(size=12),
          plot.title = element_text(hjust = 0.5, size=16), 
          legend.title = element_blank())
  
  p = grid.arrange(p1,  
                   top = textGrob("fg_bgmc_movieLib_data_c", x = 0.19, y = -1,
                                  gp=gpar(fontsize=8,font=1, col="gray47")))
  
  ggsave("fg_bgmc_movieLib_data_c.pdf", p, width = 7, height = 7)
  cat("\n.. Figure saved in", glob[["workDir"]])
  cat("\n.. returning from", thisFunction, "on", date(), "\n\n")
  
} # fg_bgmc_movieLib_data_unwatched_gg

fg_bgmc_movieLib_data_unwatched = function(fileRDS_dtPairs, fileRDS_dt) { 
  
  # a statistical model, based on 210 ... 220 trials of sampling with 
  # replacement from 11 urns, each with urn capacity of holding 210 ... 220 unique movieID tags.
  
  # Figure generated by plot function
  
  # fg_bgmc_movieLib_data_unwatched(fileRDS_dtPairs, fileRDS_dt)
  # urnSize replicaId couponsUniq couponsCover
  # 1:    1024         0         648      0.63281
  # 2:    1024         1         647      0.63184
  # 3:    1024         2         645      0.62988
  # 4:    1024         3         646      0.63086
  # 5:    1024         4         640      0.62500
  thisFunction = "fg_bgmc_movieLib_data_unwatched"
  
  dtPairs = readRDS(fileRDS_dtPairs)
  dtE     = readRDS(fileRDS_dt)
  nRows   = nrow(dtE)
  
  # plot cover-vs-size
  x = as.integer(log2(dtE$urnSize)) ; y = dtE$couponsCover
  x_min = min(x)
  x_max = max(x)
  y_min = min(y)  ; cat("\n.. y_min =", y_min, "\n")
  y_max = max(y)  ; cat(".. y_max =", y_max, "\n\n") 
  
  
  # https://stackoverflow.com/questions/4241798/how-to-increase-font-size-in-a-plot-in-r
  plot(x, y, pch=1, col="black", axes=T, cex.lab=1.1,
       xlab=paste("capacity of urns = 2^(10:20)", sep=""), 
       ylab=paste("fraction of unique movieIDs drawn with replacement after 2^(10:20) trials", sep="")
  )
  # axis(side, at=at, labels=, pos=, lty=, col=, las=, tck=, ...)
  # https://www.statmethods.net/advgraphs/axes.html
  side = 1 # bottom
  axis(side, at=x_min:x_max, cex.axis=1.1)
  side = 2 # left
  axis(side, at=seq(0.6,0.66, 0.01), cex.axis=1.1)
  
  # the population mean as the populationSize -> Inf
  # a nice illustration for the "law of large numbers"
  abline(h= 1 - exp(-1),  lwd=1, lty="dashed", col="red") 
  
  # from Eason
  # > (n = c(10, 12, 14, 16, 18,20) ); (movies = 2^n)
  # [1] 10 12 14 16 18 20
  # [1]    1024    4096   16384   65536  262144 1048576
  # unwatched = c(371, 1525, 6005, 24111, 96348, 386105)
  yW = watchedCover = 
    1 -  c(371/2^10, 1525/2^12, 6005/2^14, 24111/2^16, 96348/2^18, 386105/2^20)
  xW = c(10, 12, 14, 16, 18, 20) 
  
  for (i in 1:6) {
    points(xW[i], yW[i], pch=19, col="red", cex=1.5) 
  }
  
  legend_line = "values observed from movieLib"
  legend(12.0, 0.62, legend_line,  pch=19, col="red", cex=1.5)
  
  fg_label = "(c)"
  mtext(fg_label, col="black", cex= 1.3, side = 3, at=16.00, line=1.0) 
  
  watermark = "fg_bgmc_movieLib_data_c"
  mtext(watermark, col="gray47", cex= 0.9, side = 3, at=11.00, line=0.5) 
  
  filePdf = paste(watermark, ".pdf", sep="")
  
  cat("\n.. Figure saved in", glob[["workDir"]])
  cat("\n.. returning from", thisFunction, "on", date(), "\n\n")
  
} # fg_bgmc_movieLib_data_unwatched

rds_urn_sample_withRepl = function(urnSizes, trialSizes, replicateSize) {
  
  # Function to generate a rds file with urn sample with replacement
  thisFunction = "rds_urn_sample_withRepl"
  
  for (urnId in 1:length(urnSizes)) {
    
    urnSize   = urnSizes[urnId]
    trialSize = trialSizes[urnId]
    
    for (experimentCnt in 1:(replicateSize + 1)) {
      
      replicaId   = experimentCnt - 1
      couponsHash = hash() ; clear(couponsHash)
      coupons     = 1:urnSize
      seedInit    = replicaId ; set.seed(seedInit)
      
      for (trial in 1:trialSize) {
        
        coupon   = trunc(urnSize*runif(1))
        couponsHash[[paste(coupon)]] = ""
        
      } # for (trial in 1:trialSize)
      
      couponsUniq  = length(couponsHash)
      couponsCover = round(couponsUniq/urnSize, 5)
      
      if (replicaId == 0 && urnId == 1) {
        dt = data.table(
          urnSize = urnSize,
          replicaId = replicaId,
          couponsUniq = couponsUniq,
          couponsCover = couponsCover
        )
      } else {
        dt = rbind(dt, list(
          urnSize = urnSize,
          replicaId = replicaId,
          couponsUniq = couponsUniq,
          couponsCover = couponsCover
        ))
      }
    } # for (replicaId in 0:replicateSize
    
  } # for (urnId in 1: length(urnSizes))
  print(dt)
  
  dtPairs = data.table(
    thisFunction       = thisFunction,
    userId             = Sys.info()[["user"]], 
    cpuName            = Sys.info()[["nodename"]], 
    sysName            = Sys.info()[["sysname"]],
    dateStamp          = Sys.Date(),
    timeStamp          = format(Sys.time(), "%X"),
    "---- " = "",
    urnSizes       = paste(urnSizes, collapse=","),
    trialSizes     = paste(trialSizes, collapse=","),
    replicateSize  = replicateSize)
  
  dtPairs = t(dtPairs)
  print(dtPairs)
  
  urnSizeMax   = max(log2(urnSizes))
  trialSizeMax = max(log2(trialSizes))
  fileRDS_dt      = paste(thisFunction,  "_", urnSizeMax,   "_", trialSizeMax, "_", replicateSize, "_dt.RDS", sep="")
  fileRDS_dtPairs = paste(thisFunction,  "_", urnSizeMax,   "_", trialSizeMax, "_", replicateSize, "_dtPairs.RDS", sep="")

  curpath = getwd()
  setwd(file.path(dirname(glob[["workDir"]]), "movieRDS"))
  
  saveRDS(dt     , fileRDS_dt)
  saveRDS(dtPairs, fileRDS_dtPairs)  
  cat(sep="",
      "------------------------------------------------",
      "\n** saved datatables generated by function ", thisFunction, " in files",
      "\n   ", fileRDS_dtPairs,
      "\n   ", fileRDS_dt, 
      "\n Access any file either as",
      "\n   print(readRDS(\"", fileRDS_dtPairs, "\"))",
      "\n   print(readRDS(\"", fileRDS_dt, "\"))",
      "\n or as",
      "\n   dtPairs = readRDS(\"", fileRDS_dtPairs, "\")",
      "\n   dt      = readRDS(\"", fileRDS_dt, "\")",
      "\n\n")
  
  cat("\n.. returning from", thisFunction, "on", date(), "\n\n")
  
  setwd(curpath)
  
  
} # rds_urn_sample_withRepl

fg_bgmc_movieLib_a12 = function() {
  
  # Generate sample table to illustrate the instance
  thisFunction="fg_bgmc_movieLib_a12"
  
  movieTb = data.table(MOVIE_ID = c("tt74", "tt92", "tt01", "tt30"),
                       TITLE = c("The Story of the Kelly Gang",
                                 "Den sorte drAm",
                                 "Cleopatra",
                                 "LInferno"),
                       YEAR = c(1906, 1911, 1912, 1911),
                       RUNTIME_MINUTES = c(70, 53, 100, 68))
  
  watchTb = data.table(WATCH_ID = c("w1","w2","w3","w4","w5"),
                       MOVIE_ID = c("tt30","tt74","tt30","tt74","tt74"),
                       WATCH_DATE = c("11/21/2015","02/28/2017","04/28/2015",
                                      "09/10/2016","09/10/2017"),
                       MINUTES_WATCHED=c(64,24,16,25,15))
  
  watermark_top_a1 = "fg_bgmc_movieLib_data\n"
  watermark_top_a2 = "fg_bgmc_movieLib_data\n"
  mytheme <- gridExtra::ttheme_default(
    core = list(fg_params=list(cex = 1.5)),
    colhead = list(fg_params=list(cex = 1.0)),
    rowhead = list(fg_params=list(cex = 1.0)))
  
  dd1 <- ggplot() +
    annotation_custom(tableGrob(movieTb, rows = NULL, theme = mytheme)) +
    labs(title = '(a1) MovieRecord') +
    theme(plot.margin = margin(10,5,10,5, "pt"),
          plot.title = element_text(hjust = 0.5, size=16),
          plot.background = element_rect(fill="gray92", color = NA))
  
  
  title <- grobTree( rectGrob(gp=gpar(fill="gray92", col="gray92")), 
                     textGrob(watermark_top_a1, x = 0.04, y = -7, hjust = 0,
                              gp=gpar(fontsize=12,font=1, col="gray47")))
  
  p1 = grid.arrange(dd1, top = title)
  
  ggsave("fg_bgmc_movieLib_data_a1.pdf", p1, width = 7, height = 3)
  
  dd2 <- ggplot() +
    annotation_custom(tableGrob(watchTb, rows = NULL, theme = mytheme)) +
    labs(title = '(a2) WatchRecord') +
    theme(plot.margin = margin(10,5,10,5, "pt"),
          plot.title = element_text(hjust = 0.5, size=16),
          plot.background = element_rect(fill="gray92", color = NA))
  
  
  title <- grobTree( rectGrob(gp=gpar(fill="gray92", col="gray92")), 
                     textGrob(watermark_top_a2, x = 0.14, y = -6, hjust = 0,
                              gp=gpar(fontsize=12,font=1, col="gray47")))
  
  p2 = grid.arrange(dd2, top = title)
  
  ggsave("fg_bgmc_movieLib_data_a2.pdf", p2, width = 7, height = 3)
  cat("\n.. Figure saved in", glob[["workDir"]])
  cat("\n.. returning from", thisFunction, "on", date(), "\n\n")
} # fg_bgmc_movieLib_a12

#-----movieLib best 10 movies----
all_tests_best10 = function() { 
  # cut and paste into the R-shell any group of these commands
  source("~/__init_rBed_01.R")
  rBedPath = glob[["rBedPath"]]  
  glob[["workDir"]] = paste0(rBedPath, "/rBed_bgmc", "/bgmc_movieLib", "/workDir") 
  setwd(glob[["workDir"]])
  dataDir     = paste0(rBedPath, "/rBed_bgmc/bgmc_movieLib/movieLib/") 
  instanceDef = file.path(dataDir, "watchRecords_10.csv")
  
  fg_bgmc_movieLib_best10(instanceDef)
  
  fg_bgmc_movieLib_best10_occurrence(instanceDef)
  
} # all_tests_best10

fg_bgmc_movieLib_best10 = function(instanceDef) {
  
  # depicts the frequency of top 10 movies watched based on the instance.
  thisFunction = "fg_bgmc_movieLib_best10"
  dt = fread(instanceDef)
  dt_best10 = dt[, COUNT := 1:.N, by="MOVIE_ID"]
  dt_best10 = unique(dt_best10, by="MOVIE_ID", fromLast = T)
  dt_best10 = head(dt_best10[order(-COUNT)], 10)
  dt_best10 = dt_best10[,c("MOVIE_ID", "COUNT")]
  
  cat("\n...Top 10 movies\n")
  
  # print(dt_best10)
  
  dt_best10$START = 0
  dt_best10$idx = seq(nrow(dt_best10))
  
  # print(dt_best10)
  # ...Top 10 movies
  #     MOVIE_ID COUNT START idx
  # 1: rivdpbpzb     9     0   1
  # 2: hfagnutxq     8     0   2
  # 3: fqdqgwjbe     8     0   3
  # 4: xivrbrexd     8     0   4
  # 5: aaabfidgn     8     0   5
  # 6: nbarpuura     8     0   6
  # 7: ekdunuezc     8     0   7
  # 8: qmjdhvpym     8     0   8
  # 9: kyosyinqz     8     0   9
  # 10: tt0125678    7     0  10
  
  sp2 = ggplot(data=dt_best10, aes(x=idx))  +
    geom_segment(aes(x = idx, y = START, xend = idx, yend = COUNT), col="red", lwd=1) + 
    geom_point(y=dt_best10$COUNT) + 
    geom_point(y=dt_best10$START) +
    scale_x_continuous(labels = as.character(dt_best10$idx), breaks = dt_best10$idx) +
    labs(x="Index of top 10 movies", y="Number of occurrence for movieLib") +
    labs(title = "(a)") +
    theme(legend.position = c(0.3, 0.6), legend.key.size = unit(.3, 'inch'),
          legend.text = element_text(size=15),
          plot.title = element_text(size=10, hjust = 0.5))
  
  p = grid.arrange(sp2,  
                   top = textGrob("fg_bgmc_movieLib_best10", x = 0.18, y = -1,
                                  gp=gpar(fontsize=8,font=1, col="gray47")))
  
  
  ggsave("fg_bgmc_movieLib_best10.pdf", p, width = 7, height = 3.5)
  cat("\n.. Figure saved in", glob[["workDir"]])
  cat("\n.. returning from", thisFunction, "on", date(), "\n\n")
} # fg_bgmc_movieLib_best10

fg_bgmc_movieLib_best10_occurrence = function(instanceDef) {
  # counts the total number of movies watched based on the instance
  thisFunction = "fg_bgmc_movieLib_best10_occurrence"
  cat("\n...this function generates a plot where it counts how many 
      movies have been watched a certain number of times..\n")
  
  fileBase   = my_file_root(instanceDef)  
  fileExt    = my_file_ext(instanceDef)
  stopifnot(fileExt == "csv")
  
  df = fread(instanceDef) ;# print(df) ;# create a dataframe 
  
  dt = df[,count := 1:.N, by="MOVIE_ID"]
  dt = unique(dt, by="MOVIE_ID", fromLast = T)
  count_max = max(dt$count)
  
  occ = rep(NA, count_max)
  for (i in 1:count_max) {
    val = nrow(dt[count==i,])
    occ[i] = val
  }
  dt = data.table(N=occ, watchedFreqV=seq(length(occ)), start=1)
  
  # print(dt)
  # N watchedFreqV start
  # 1: 385128            1     1
  # 2: 193048            2     1
  # 3:  64321            3     1
  # 4:  16171            4     1
  # 5:   3207            5     1
  # 6:    512            6     1
  # 7:     75            7     1
  # 8:      8            8     1
  # 9:      1            9     1
  
  sp2 = ggplot(data=dt, aes(x=watchedFreqV))  +
    
    scale_y_log10() +
    geom_point(aes(y=N)) + 
    
    geom_segment(aes(x = watchedFreqV, y = start, xend = watchedFreqV, yend = N),
                 col="red", lwd=1) + 
    
    geom_point(aes(y=start)) +
    
    scale_x_continuous(labels = as.character(dt$watchedFreqV), breaks = dt$watchedFreqV) +
    labs(x="Index for movie occurrences", y="Number of watched movies with specific times") +
    labs(title = "(b)") +
    theme(legend.position = c(0.3, 0.6), legend.key.size = unit(.3, 'inch'),
          legend.text = element_text(size=15),
          plot.title = element_text(size=10, hjust = 0.5)) 
  
  p = grid.arrange(sp2,  
                   top = textGrob("fg_bgmc_movieLib_best10_occurrence", x = 0.25, y = -1,
                                  gp=gpar(fontsize=8,font=1, col="gray47")))
  
  ggsave("fg_bgmc_movieLib_best10_occurrence.pdf", p, width = 7, height = 3.5)
  cat("\n.. Figure saved in", glob[["workDir"]])
  cat("\n.. returning from", thisFunction, "on", date(), "\n\n")
  
} # fg_bgmc_movieLib_best10_occurrence






